# Generated by Django 3.1.1 on 2020-09-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('inquiry_type', models.CharField(choices=[('【Uvey】サービスに関するお問い合わせ', '【Uvey】サービスに関するお問い合わせ'), ('【Uvey】サービスに関するご意見・ご要望', '【Uvey】サービスに関するご意見・ご要望'), ('その他', 'その他')], max_length=100, verbose_name='概要する問合せ')),
                ('inquiry', models.TextField(verbose_name='お問合せ内容')),
            ],
            options={
                'verbose_name': 'お問合せ',
                'verbose_name_plural': 'お問合せ',
            },
        ),
    ]
