# Generated by Django 3.1.1 on 2020-09-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200918_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='sample', max_length=30, verbose_name='お名前'),
            preserve_default=False,
        ),
    ]
