# Generated by Django 3.1.1 on 2020-09-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='target',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
